name: minio

x-minio-common: &minio-common
  # image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
  image: quay.io/minio/minio
  command: server --address ":9000" --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
  healthcheck:
    test: 
      - CMD-SHELL
      - mc ready local
    interval: 5s
    timeout: 5s
    retries: 5
  networks:
    - projeto-lakehouse
  restart: always

services:
  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    container_name: minio4
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - mode: ingress
        target: 9000
        published: "${MINIO_API_PORT}"
        protocol: tcp
      - mode: ingress
        target: 9001
        published: "${MINIO_WEBUI_PORT}"
        protocol: tcp
    depends_on:
      minio1:
        condition: service_healthy
        required: true
      minio2:
        condition: service_healthy
        required: true
      minio3:
        condition: service_healthy
        required: true
      minio4:
        condition: service_healthy
        required: true
    networks:
      - projeto-lakehouse
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: always

networks:
  projeto-lakehouse:
    name: projeto-lakehouse
    external: true
 
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: